### ISSUE TITLE
Can't run module

### ISSUE THREAD

**Issue by ChrisGehm** [sp4ceman/MMM-googlemaps#1]
Hi, I was trying to run the module on the MM2, followed the steps, but when I run it it only appears a black screen. Any idea why?
Kind regards

**Comment by sp4ceman** [comment]
hmm not sure, tbh i haven't used this in a while so i dont know if maybe they've changed their api or something. what i would suggest is modify the script to output or console.log the "fullyBuiltURL" variable. then try open that url in a browser and check in the dev tools if there are errors

there are also only 3 variables.. your api key, your origin and your destination so obviously double check those :)

**Comment by macxs** [comment]
I had the same problem earlier today. Make sure your API is activated and your origin and destination are formated like google does.
`              {
                      module: 'googlemap',
                      position: 'top_right',
                      config: {
                             apikey: 'YourApiKeyHere',
                             origin: 'Hauptstraße+199,+YourPostalCode+YourLocation',
                             destination: 'Hauptstraße+37,+SomePostalCode+SomeLocation'
                      }
                },`
