### ISSUE TITLE
Module is not properly installed

### ISSUE THREAD

**Issue by caldecy** [sp4ceman/MMM-googlemaps#2]
I downloaded the module into the wrong directory during the installation process. It was initially downloaded into my **/home/pi** directory but I have since **cut** and **paste** the entire folder into the /home/pi/MagicMirror/modules directory. Afterwhich, I ran the Magic Mirror app but the Google Maps does not seem to even be running in the boot up. 

A simple one line during my boot up shows this script: 
```No helper found for module: googlemap.```

Anyone has any ideas on how to run the module properly? Maybe a step that I have missed out to install the module properly?

**Comment by caldecy** [comment]
This is the error message I get when I try to **npm install** in the **cd MMM-googlemaps** directory:

```
pi@raspi_chu:~/MagicMirror/modules/MMM-googlemaps $ npm install
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/node_modules/node_helper/package.json'
npm WARN modules No description
npm WARN modules No repository field.
npm WARN modules No README data
npm WARN modules No license field.
```

**Comment by sp4ceman** [comment]
inside MMM-googlemaps is the "googlemap" folder.
this is the only folder you need to put in your magicmirror/modules 

the path to the script should be :
MagicMirror/modules/googlemap/googlemap.js

**Comment by caldecy** [comment]
Alright! Thank you!
